name: DevTest
on:
  push:
    branchs:
      - dev
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    name: Lint-UT
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Set up MySQL
        uses: shogo82148/actions-setup-mysql@v1.12.0
        with:
          mysql-version: '8.0'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Go Code
        run: |
          go install golang.org/x/lint/golint@latest
          golint -set_exit_status $(go list ./... | grep -v vendor)

      - name: Run Unit tests.
        run: |
          chmod +x test.sh
          ./test.sh
